/**
 * APIKEY provider catalog — regional family (China + other regional providers).
 * Pure data; merged by apikey/index.ts via spread (god-file decomposition; semantic split).
 */
export const APIKEY_PROVIDERS_REGIONAL = {
  qianfan: {
    id: "qianfan",
    serviceKinds: ["llm"],
    alias: "qianfan",
    name: "Baidu Qianfan",
    icon: "cloud",
    color: "#2468F2",
    textIcon: "BD",
    website: "https://cloud.baidu.com/product-s/qianfan_home",
    apiHint:
      "Use a Qianfan API key from Baidu AI Cloud. The default endpoint is OpenAI-compatible v2.",
  },
  glm: {
    id: "glm",
    serviceKinds: ["llm"],
    alias: "glm",
    name: "GLM Coding",
    icon: "code",
    color: "#2563EB",
    textIcon: "GL",
    website: "https://z.ai/subscribe",
  },
  "glm-cn": {
    id: "glm-cn",
    serviceKinds: ["llm"],
    alias: "glmcn",
    name: "GLM Coding (China)",
    icon: "code",
    color: "#DC2626",
    textIcon: "GC",
    website: "https://open.bigmodel.cn",
  },
  bigmodel: {
    id: "bigmodel",
    serviceKinds: ["llm"],
    alias: "bigmodel",
    name: "BigModel.cn (Zhipu)",
    icon: "psychology",
    color: "#2563EB",
    textIcon: "BM",
    website: "https://open.bigmodel.cn",
    apiHint:
      "Create an API key at https://bigmodel.cn/usercenter/proj-mgmt/apikeys. OmniRoute uses BigModel.cn's OpenAI-compatible chat API.",
    passthroughModels: true,
  },
  glmt: {
    id: "glmt",
    serviceKinds: ["llm"],
    alias: "glmt",
    name: "GLM Thinking",
    icon: "psychology",
    color: "#1D4ED8",
    textIcon: "GT",
    website: "https://open.bigmodel.cn",
    apiHint: "Preset GLM profile with higher token budget, thinking enabled, and longer timeout.",
  },
  "bailian-coding-plan": {
    id: "bailian-coding-plan",
    serviceKinds: ["llm"],
    alias: "bcp",
    name: "Alibaba Token Plan",
    icon: "code",
    color: "#FF6A00",
    textIcon: "BCP",
    website: "https://www.alibabacloud.com/help/en/model-studio/token-plan-overview",
    apiHint: "Use an Alibaba Token Plan key and select its Singapore or Beijing region.",
  },
  "qwen-cloud": {
    id: "qwen-cloud",
    serviceKinds: ["llm"],
    alias: "qwc",
    name: "Qwen Cloud",
    icon: "cloud",
    color: "#615CED",
    textIcon: "QC",
    website: "https://www.qwencloud.com/",
    apiHint: "Use a Qwen Cloud API key and select its Global or Beijing region.",
  },
  "qwen-cloud-token-plan": {
    id: "qwen-cloud-token-plan",
    serviceKinds: ["llm"],
    alias: "qct",
    name: "Qwen Cloud Token Plan",
    icon: "cloud",
    color: "#615CED",
    textIcon: "QCT",
    website: "https://www.qwencloud.com/pricing/token-plan",
    apiHint: "Use a Qwen Cloud Token Plan key and select its Singapore or Beijing region.",
  },
  kimi: {
    id: "kimi",
    serviceKinds: ["llm"],
    alias: "kimi",
    name: "Kimi (Legacy Moonshot API)",
    icon: "psychology",
    color: "#1E3A8A",
    textIcon: "KM",
    // Kimi official-partnership aff link (2026-07) — see KIMI_PROVIDER_IDS in
    // featuredProviders.ts. hiddenFromDashboard, so this rarely renders, but is
    // kept in sync with moonshot's aff link for consistency.
    website: "https://platform.kimi.ai?aff=omniroute",
    hiddenFromDashboard: true,
  },
  "kimi-coding-apikey": {
    id: "kimi-coding-apikey",
    serviceKinds: ["llm"],
    alias: "kmca",
    name: "Kimi Code API Key",
    icon: "psychology",
    color: "#1E40AF",
    textIcon: "KC",
    // Kimi official-partnership aff link (2026-07) — folds into the kimi-coding
    // card (PROVIDER_CONNECTION_ALIASES in providerPageUtils.ts) so this rarely
    // renders its own header, but stays in sync with kimi-coding's aff link.
    website: "https://www.kimi.ai/code?aff=omniroute",
    hiddenFromDashboard: true,
  },
  minimax: {
    id: "minimax",
    serviceKinds: ["llm"],
    alias: "minimax",
    name: "Minimax Coding",
    icon: "memory",
    color: "#7C3AED",
    textIcon: "MM",
    website: "https://www.minimax.io",
  },
  "minimax-cn": {
    id: "minimax-cn",
    serviceKinds: ["llm"],
    alias: "minimax-cn",
    name: "Minimax (China)",
    icon: "memory",
    color: "#DC2626",
    textIcon: "MC",
    website: "https://www.minimaxi.com",
  },
  deepseek: {
    id: "deepseek",
    serviceKinds: ["llm"],
    alias: "ds",
    name: "DeepSeek",
    icon: "bolt",
    color: "#4D6BFE",
    textIcon: "DS",
    website: "https://platform.deepseek.com",
    hasFree: true,
    freeNote: "5M free tokens on signup - no credit card required",
  },
  zai: {
    id: "zai",
    serviceKinds: ["llm"],
    alias: "zai",
    name: "Z.AI",
    icon: "psychology",
    color: "#2563EB",
    textIcon: "ZA",
    website: "https://z.ai/model-api",
    apiHint: "Create an API key at https://z.ai/manage-apikey/apikey-list.",
  },
  alibaba: {
    id: "alibaba",
    serviceKinds: ["llm"],
    alias: "ali",
    name: "Alibaba Cloud Model Studio",
    icon: "cloud_queue",
    color: "#FF6600",
    textIcon: "AL",
    website: "https://bailian.console.alibabacloud.com/",
    hasFree: false,
    apiHint: "Use a Model Studio API key and select its Singapore or Beijing region.",
  },
  "alibaba-cn": {
    id: "alibaba-cn",
    serviceKinds: ["llm"],
    alias: "ali-cn",
    name: "Alibaba (China)",
    icon: "cloud_queue",
    color: "#FF6600",
    textIcon: "AL",
    website: "https://dashscope.console.aliyun.com/",
    hasFree: false,
    hiddenFromDashboard: true,
  },
  longcat: {
    id: "longcat",
    serviceKinds: ["llm"],
    alias: "lc",
    name: "LongCat AI",
    icon: "auto_awesome",
    color: "#FF6B9D",
    textIcon: "LC",
    website: "https://longcat.chat/platform/docs",
    hasFree: true,
    freeNote:
      "Free: one-time 10M-token grant after account signup + KYC verification (LongCat-2.0). One-time only — not a recurring daily/monthly allowance.",
  },
  moonshot: {
    id: "moonshot",
    serviceKinds: ["llm"],
    alias: "moonshot",
    // Display name only — Kimi official-partnership rebrand (2026-07). The
    // catalog id/alias/routing stay "moonshot" (DB connections, combos, and
    // /dashboard/providers/moonshot all address it by id, never by name) — see
    // KIMI_PROVIDER_IDS in featuredProviders.ts for the full id list this
    // touches. "Kimi (Legacy Moonshot API)" (id "kimi") and "Moonshot AI" in
    // company-name mentions (e.g. README, kimiOfficialSupporterTooltip) are
    // intentionally left as-is.
    name: "Kimi",
    icon: "rocket_launch",
    color: "#1E40AF",
    textIcon: "MS",
    // Kimi official-partnership aff link (2026-07): the "Kimi API Platform"
    // tracking link — was the unattributed legacy platform.moonshot.ai domain
    // (301s to platform.kimi.ai with no aff tag).
    website: "https://platform.kimi.ai?aff=omniroute",
  },
  volcengine: {
    id: "volcengine",
    serviceKinds: ["llm"],
    alias: "volcengine",
    name: "Volcengine",
    icon: "local_fire_department",
    color: "#DC2626",
    textIcon: "VE",
    website: "https://www.volcengine.com",
  },
  "volcengine-agent-plan": {
    id: "volcengine-agent-plan",
    serviceKinds: ["llm"],
    alias: "veap",
    name: "Volcengine Ark Agent Plan",
    icon: "local_fire_department",
    color: "#DC2626",
    textIcon: "VA",
    website: "https://console.volcengine.com/ark/region:cn-beijing/subscription/agent-plan",
    authHint: "Connect your Volcano Engine account or use an Ark Agent Plan subscription API key.",
  },
  "volcengine-coding-plan": {
    id: "volcengine-coding-plan",
    serviceKinds: ["llm"],
    alias: "vecp",
    name: "Volcengine Ark Coding Plan",
    icon: "code",
    color: "#FF6A00",
    textIcon: "VC",
    website: "https://console.volcengine.com/ark/region:cn-beijing/subscription/coding-plan",
    authHint: "Connect your Volcano Engine account or use an Ark Coding Plan subscription API key.",
  },
  gigachat: {
    id: "gigachat",
    serviceKinds: ["llm"],
    alias: "gigachat",
    name: "GigaChat (Sber)",
    icon: "lock_person",
    color: "#10B981",
    textIcon: "GC",
    website: "https://developers.sber.ru",
  },
  "xiaomi-mimo": {
    id: "xiaomi-mimo",
    serviceKinds: ["llm"],
    alias: "mimo",
    name: "Xiaomi MiMo",
    icon: "devices",
    color: "#EA580C",
    textIcon: "MM",
    website: "https://mimo.mi.com",
  },
  "xiaomi-mimo-token-plan": {
    id: "xiaomi-mimo-token-plan",
    serviceKinds: ["llm"],
    alias: "mimotp",
    name: "Xiaomi MiMo Token Plan",
    icon: "devices",
    color: "#EA580C",
    textIcon: "MT",
    website: "https://mimo.mi.com",
    apiHint:
      "Use a Token Plan key (tp-…) and select the cluster (Singapore, Amsterdam, or China) that issued it.",
  },
  baidu: {
    id: "baidu",
    serviceKinds: ["llm"],
    alias: "baidu",
    name: "Baidu (ERNIE)",
    icon: "auto_awesome",
    color: "#2932E1",
    textIcon: "BD",
    website: "https://ernie.baidu.com/",
    hasFree: true,
    freeNote: "Free ERNIE Speed/Lite models. China's #2 LLM.",
    passthroughModels: true,
    authHint: "Get API key at console.bce.baidu.com",
  },
  tencent: {
    id: "tencent",
    serviceKinds: ["llm"],
    alias: "tencent",
    name: "Tencent Hunyuan",
    icon: "auto_awesome",
    color: "#07C160",
    textIcon: "TC",
    website: "https://hunyuan.tencent.com",
    hasFree: true,
    freeNote: "Free Hunyuan Lite models. WeChat ecosystem.",
    passthroughModels: true,
    authHint: "Get API key at console.cloud.tencent.com",
  },
  iflytek: {
    id: "iflytek",
    serviceKinds: ["llm"],
    alias: "iflytek",
    name: "iFlytek Spark",
    icon: "auto_awesome",
    color: "#0066FF",
    textIcon: "IF",
    website: "https://xinghuo.xfyun.cn",
    hasFree: true,
    freeNote:
      "Spark Lite is free (2 QPS rate-limited), but iFlytek ToS §2.4(3) prohibits programmatic extraction and requires Chinese real-name auth — use with caution.",
    passthroughModels: true,
    authHint: "Get API key at console.xfyun.cn",
  },
  baichuan: {
    id: "baichuan",
    serviceKinds: ["llm"],
    alias: "baichuan",
    name: "Baichuan",
    icon: "auto_awesome",
    color: "#6366F1",
    textIcon: "BC",
    website: "https://www.baichuan-ai.com/",
    hasFree: true,
    freeNote: "Free Baichuan models. Popular Chinese LLM startup.",
    passthroughModels: true,
    authHint: "Get API key at platform.baichuan-ai.com",
  },
  yi: {
    id: "yi",
    serviceKinds: ["llm"],
    alias: "yi",
    name: "Yi (01.AI)",
    icon: "auto_awesome",
    color: "#10B981",
    textIcon: "YI",
    website: "https://01.ai",
    hasFree: false,
    freeNote:
      "No free API tier (2026) — Yi-Light retired; platform.01.ai is pay-as-you-go (Yi-Lightning paid). Open weights are download-only.",
    passthroughModels: true,
    authHint: "Get API key at platform.lingyiwanwu.com",
  },
  stepfun: {
    id: "stepfun",
    serviceKinds: ["llm"],
    alias: "stepfun",
    name: "StepFun",
    icon: "auto_awesome",
    color: "#8B5CF6",
    textIcon: "SF",
    website: "https://stepfun.com",
    hasFree: true,
    freeNote: "Free Step-2 models. Chinese AI company.",
    passthroughModels: true,
    authHint: "Get API key at platform.stepfun.com",
    // #5462 — this integration calls StepFun's China platform (api.stepfun.com),
    // whose sign-up appears to be phone-based. International users have a separate
    // global platform (platform.stepfun.ai, operated by Sparkling AI Pte Ltd,
    // Singapore) with email/Google/Discord login. Keys are NOT interchangeable:
    // a key from one platform 401s against the other. Operators with an
    // international key set the connection's custom base URL to
    // https://api.stepfun.ai/v1 (honored via providerSpecificData.baseUrl).
    notice: {
      text: "This connects to StepFun's China platform (platform.stepfun.com), whose sign-up appears to require a Chinese phone number. Users outside mainland China can instead register at the global StepFun Open Platform (platform.stepfun.ai, operated by Sparkling AI Pte. Ltd., Singapore) with email/Google/Discord login. Keys are not interchangeable between the two platforms — with an international key, set this connection's custom base URL to https://api.stepfun.ai/v1.",
      signupUrl: "https://platform.stepfun.ai",
    },
  },
  coze: {
    id: "coze",
    serviceKinds: ["llm"],
    alias: "coze",
    name: "Coze",
    icon: "smart_toy",
    color: "#3B82F6",
    textIcon: "CZ",
    website: "https://coze.com",
    hasFree: true,
    freeNote: "Free ByteDance agent platform. Bot building + LLM access.",
    passthroughModels: true,
    authHint: "Get API key at coze.com/open/api",
  },
  "360ai": {
    id: "360ai",
    serviceKinds: ["llm"],
    alias: "360ai",
    name: "360 AI",
    icon: "auto_awesome",
    color: "#00B96B",
    textIcon: "360",
    website: "https://ai.360.cn",
    hasFree: true,
    freeNote: "Free 360 AI Brain models. Major Chinese security company.",
    passthroughModels: true,
    authHint: "Get API key at ai.360.cn",
  },
  doubao: {
    id: "doubao",
    serviceKinds: ["llm"],
    alias: "doubao",
    name: "Doubao",
    icon: "auto_awesome",
    color: "#FE2C55",
    textIcon: "DB",
    website: "https://doubao.com",
    hasFree: true,
    freeNote: "Free Doubao models. ByteDance's chatbot.",
    passthroughModels: true,
    authHint: "Get API key at console.volcengine.com",
  },
  sensenova: {
    id: "sensenova",
    serviceKinds: ["llm"],
    alias: "sensenova",
    name: "SenseNova",
    icon: "auto_awesome",
    color: "#0066FF",
    textIcon: "SN",
    website: "https://platform.sensenova.cn",
    hasFree: true,
    freeNote: "Free SenseTime models. Computer vision leader.",
    passthroughModels: true,
    authHint: "Get API key at platform.sensenova.cn",
    // #5462 — SenseNova's console (platform.sensenova.cn) appears to require a
    // Chinese (+86) phone number for SMS-verified registration, with no documented
    // international sign-up path. Warn users outside mainland China up front.
    notice: {
      text: "SenseNova registration appears to require a Chinese (+86) phone number for SMS verification — no international sign-up path is documented, so users outside mainland China may be unable to obtain an API key.",
      signupUrl: "https://platform.sensenova.cn/console",
    },
  },
  sparkdesk: {
    id: "sparkdesk",
    serviceKinds: ["llm"],
    alias: "sparkdesk",
    name: "SparkDesk",
    icon: "auto_awesome",
    color: "#0066FF",
    textIcon: "SD",
    website: "https://xinghuo.xfyun.cn",
    hasFree: true,
    freeNote:
      "Spark Lite free (alias for iflytek), but ToS restricts to personal/non-commercial use and prohibits relaying access to third parties — use with caution.",
    passthroughModels: true,
    authHint: "Get API key at console.xfyun.cn",
  },
  hcnsec: {
    id: "hcnsec",
    serviceKinds: ["llm"],
    alias: "hcnsec",
    name: "Huancheng Public API",
    icon: "security",
    color: "#0EA5E9",
    textIcon: "HC",
    website: "https://api.hcnsec.cn",
    hasFree: true,
    freeNote:
      "Xinjiang Huancheng Cybersecurity public LLM API platform: free credits with daily check-ins.",
    passthroughModels: true,
    authHint: "Get API key at api.hcnsec.cn",
  },
  agnes: {
    id: "agnes",
    serviceKinds: ["llm"],
    alias: "agnes",
    name: "Agnes AI",
    icon: "auto_awesome",
    color: "#10B981",
    textIcon: "AG",
    website: "https://agnes-ai.com",
    hasFree: true,
    freeNote: "Permanently free API - no credit card required.",
    authHint: "Get API key at agnes-ai.com",
  },
  "agnes-cn": {
    id: "agnes-cn",
    serviceKinds: ["llm"],
    alias: "agnescn",
    name: "Agnes AI (China)",
    icon: "auto_awesome",
    color: "#047857",
    textIcon: "AC",
    website: "https://api.agnes-ai.cn",
    hasFree: true,
    freeNote: "Permanently free, no API credit card required.",
    authHint: "Get API key from the Agnes CN site.",
  },
  sealion: {
    id: "sealion",
    serviceKinds: ["llm"],
    alias: "sealion",
    name: "SEA-LION",
    icon: "public",
    color: "#0D9488",
    textIcon: "SL",
    website: "https://sea-lion.ai",
    hasFree: true,
    freeNote:
      "Permanently free at 10 RPM — AI Singapore's Southeast-Asian models (Llama/Qwen/Gemma SEA-LION).",
    authHint:
      "Sign in at sea-lion.ai with Google (no card, no region wall), create an API key, then paste it here.",
  },
  "clova-studio": {
    id: "clova-studio",
    serviceKinds: ["llm"],
    alias: "clova",
    name: "Naver CLOVA Studio",
    icon: "auto_awesome",
    color: "#03C75A",
    textIcon: "CS",
    website: "https://api.ncloud-docs.com/docs/en/ai-naver-clovastudio-summary",
    apiHint:
      "OmniRoute routes chat traffic to the native Chat Completions v3 API (/v3/chat-completions/{model}), not the OpenAI-compatibility shim. All three v3 models are served: HCX-007 (reasoning, text only), HCX-005 (vision — accepts both public image URLs and inline base64 images), and HCX-DASH-002 (lightweight, text only). Requests stream upstream and are accumulated into a JSON body when the client asks for a non-streaming response.",
  },
  internlm: {
    id: "internlm",
    serviceKinds: ["llm"],
    alias: "internlm",
    name: "InternLM (Intern-S1)",
    icon: "auto_awesome",
    color: "#4F46E5",
    textIcon: "IL",
    website: "https://internlm.intern-ai.org.cn/",
    hasFree: true,
    freeNote: "Free monthly quota ~1M input / 3M output tokens (~10 RPM)",
  },
  "ant-ling": {
    id: "ant-ling",
    serviceKinds: ["llm"],
    alias: "ling",
    name: "Ant Ling / Ring (inclusionAI)",
    icon: "auto_awesome",
    color: "#1677FF",
    textIcon: "AL",
    website: "https://developer.ant-ling.com/en/docs/",
    hasFree: true,
    freeNote: "500,000 free tokens per day per account (resets 02:00 UTC+8, no rollover)",
    authHint:
      "Register and create an API key at the Ant Ling API console (https://chat.ant-ling.com/open), then paste it here. OmniRoute routes chat traffic to https://api.ant-ling.com/v1/chat/completions; the provider is OpenAI-compatible and also exposes an Anthropic-compatible surface.",
  },
  sarvam: {
    id: "sarvam",
    serviceKinds: ["llm"],
    alias: "sarvam",
    name: "Sarvam AI",
    icon: "public",
    color: "#0EA5E9",
    textIcon: "SV",
    website: "https://docs.sarvam.ai",
    apiHint:
      "Sarvam AI is OpenAI-compatible on /v1. OmniRoute probes /v1/models and routes chat traffic to /v1/chat/completions. Models are tuned for Indic languages.",
    hasFree: true,
    freeNote: "₹1,000 in free signup credits — never expire",
  },
  plamo: {
    id: "plamo",
    serviceKinds: ["llm"],
    alias: "plamo",
    name: "PLaMo",
    icon: "public",
    color: "#DC2626",
    textIcon: "PL",
    website: "https://plamo.preferredai.jp/api",
    apiHint:
      "PLaMo is OpenAI-compatible at https://api.platform.preferredai.jp/v1. Built by Preferred Networks and optimized for Japanese. Docs are primarily in Japanese.",
    hasFree: false,
  },
  typhoon: {
    id: "typhoon",
    serviceKinds: ["llm"],
    alias: "typhoon",
    name: "Typhoon",
    icon: "public",
    color: "#7C3AED",
    textIcon: "TY",
    website: "https://docs.opentyphoon.ai",
    apiHint:
      "Typhoon is OpenAI-compatible on /v1. Built by SCB 10X (Thailand); typhoon-v2.5-30b-a3b-instruct is a thai-first, multilingual model.",
    hasFree: true,
    freeNote: "Free API key with a 5 req/s and 200 req/m rate limit.",
  },
  apmix: {
    id: "apmix",
    serviceKinds: ["llm"],
    alias: "apmix",
    name: "Apmix",
    icon: "hub",
    color: "#7C3AED",
    textIcon: "AP",
    website: "https://apmix.ai",
    apiHint: "Get your API key from the Apmix dashboard (apmix.ai/dashboard).",
  },
};
