/**
 * Provider catalog data — extracted from providers.ts (god-file decomposition).
 * Pure data literal; re-exported by the providers.ts barrel. No behavior change.
 */
import { GITLAB_DUO_OAUTH_SETUP_MESSAGE } from "@/shared/constants/gitlabDuoSetupMessage";

export const OAUTH_PROVIDERS = {
  "ghe-copilot": {
    id: "ghe-copilot",
    serviceKinds: ["llm"],
    alias: "ghe-copilot",
    name: "GitHub Enterprise Copilot",
    icon: "code",
    color: "#10B981",
    subscriptionRisk: true,
    riskNoticeVariant: "oauth",
    authHint:
      "Enter your GHE instance URL (e.g., https://ghe.company.com) in provider settings, then authenticate via device flow.",
  },
  "xai-oauth": {
    id: "xai-oauth",
    serviceKinds: ["llm"],
    alias: "xao",
    name: "xAI OAuth (Grok)",
    icon: "auto_awesome",
    color: "#1DA1F2",
    textIcon: "XA",
    website: "https://x.ai",
    subscriptionRisk: true,
    riskNoticeVariant: "oauth",
    // Render xAI OAuth through the unified xAI dashboard card. Keep this
    // catalog entry addressable for existing routes and stored connections.
    hiddenFromDashboard: true,
    authHint:
      "Sign in with xAI to use api.x.ai models such as Grok 4.5. This is separate from Grok Build JWT sessions, which use cli-chat-proxy.grok.com and grok-build model aliases.",
  },
  openference: {
    id: "openference",
    serviceKinds: ["llm"],
    alias: "of",
    name: "Openference",
    icon: "openference",
    color: "#6366F1",
    textIcon: "OF",
    website: "https://openference.com",
    hasFree: true,
    freeNote:
      "Free tier: includes Qwen3.8 27b and Llama 3.2 3B — see openference.com/pricing for current terms",
    authHint:
      "Sign in with your Openference account to route requests through api.openference.com. Includes free-tier access to Qwen3.8 27b and Llama 3.2 3B — see openference.com/pricing for current plan terms.",
  },
  "grok-cli": {
    id: "grok-cli",
    serviceKinds: ["llm"],
    alias: "gc",
    name: "Grok Build",
    icon: "bolt",
    color: "#000000",
    subscriptionRisk: true,
    riskNoticeVariant: "oauth",
    authHint:
      "Sign in with your browser, or paste your ~/.grok/auth.json (or the JWT access token) from the Grok Build CLI; refresh_token is rotated automatically either way.",
  },
  qoder: {
    id: "qoder",
    serviceKinds: ["llm"],
    alias: "if",
    name: "Qoder",
    authHint:
      "PAT (pt-): requires local qodercli; plain chat only, no caller tools, buffered streaming and a 45-second chat limit. HTTP keys use DashScope; browser OAuth requires administrator configuration.",
    icon: "water_drop",
    color: "#6366F1",
    subscriptionRisk: true,
    riskNoticeVariant: "oauth",
    hasFree: true,
  },
  agy: {
    id: "agy",
    serviceKinds: ["llm"],
    alias: "agy",
    name: "Antigravity CLI",
    icon: "terminal",
    color: "#F59E0B",
    textIcon: "AGY",
    website: "https://antigravity.google",
    subscriptionRisk: true,
    riskNoticeVariant: "oauth",
    hasFree: true,
    authHint:
      "Import your Antigravity CLI (`agy`) login (paste/upload its token file), auto-detect a local CLI login, or sign in with Google. Shares the Antigravity backend (incl. Claude models).",
  },
  kiro: {
    id: "kiro",
    serviceKinds: ["llm"],
    alias: "kr",
    name: "Kiro AI",
    icon: "psychology_alt",
    color: "#FF6B35",
    subscriptionRisk: true,
    riskNoticeVariant: "deprecated",
    hasFree: true,
    freeNote:
      "Free tier: 50 credits/month (~25K–100K tokens). ⚠️ Kiro ToS prohibits third-party proxy/harness use.",
  },
  "amazon-q": {
    id: "amazon-q",
    serviceKinds: ["llm"],
    alias: "aq",
    name: "Amazon Q",
    icon: "cloud",
    color: "#FF9900",
    textIcon: "AQ",
    website: "https://aws.amazon.com/q/developer/",
    hasFree: true,
    authHint:
      "Uses the same AWS Builder ID or imported refresh-token flow as Kiro, but keeps Amazon Q connections separate.",
  },
  claude: {
    id: "claude",
    serviceKinds: ["llm"],
    alias: "cc",
    name: "Claude Code",
    icon: "smart_toy",
    color: "#D97757",
    subscriptionRisk: true,
    riskNoticeVariant: "oauth",
  },
  antigravity: {
    id: "antigravity",
    serviceKinds: ["llm"],
    alias: undefined,
    name: "Antigravity",
    icon: "rocket_launch",
    color: "#F59E0B",
    subscriptionRisk: true,
    riskNoticeVariant: "oauth",
  },
  codex: {
    id: "codex",
    serviceKinds: ["llm"],
    alias: "cx",
    name: "OpenAI Codex",
    icon: "code",
    color: "#3B82F6",
    subscriptionRisk: true,
    riskNoticeVariant: "oauth",
  },
  github: {
    id: "github",
    serviceKinds: ["llm"],
    alias: "gh",
    name: "GitHub Copilot",
    icon: "code",
    color: "#333333",
  },
  "gitlab-duo": {
    id: "gitlab-duo",
    serviceKinds: ["llm"],
    alias: "gitlab-duo",
    name: "GitLab Duo",
    icon: "hub",
    color: "#FC6D26",
    textIcon: "GL",
    website: "https://docs.gitlab.com/user/duo_agent_platform/code_suggestions/",
    // #8688: full actionable recipe (same string as authorize error + OAuthModal setup step)
    authHint: GITLAB_DUO_OAUTH_SETUP_MESSAGE,
  },
  cursor: {
    id: "cursor",
    serviceKinds: ["llm"],
    alias: "cu",
    name: "Cursor IDE",
    icon: "edit_note",
    color: "#00D4AA",
    subscriptionRisk: true,
    riskNoticeVariant: "oauth",
  },
  zed: {
    id: "zed",
    serviceKinds: ["llm"],
    alias: "zd",
    name: "Zed IDE",
    icon: "code",
    color: "#084CCF",
    textIcon: "ZD",
    website: "https://zed.dev",
    authHint:
      "Zed stores LLM provider credentials (OpenAI, Anthropic, Google, Mistral, xAI) in the OS keychain. Use the Import button below to discover and import them automatically.",
  },
  "zed-hosted": {
    id: "zed-hosted",
    serviceKinds: ["llm"],
    alias: undefined,
    name: "Zed Hosted Models",
    icon: "code_blocks",
    color: "#101010",
    textIcon: "ZH",
    website: "https://zed.dev",
    subscriptionRisk: true,
    riskNoticeVariant: "oauth",
    authHint:
      "Sign in with your Zed account (native-app sign-in). OmniRoute generates a one-time RSA keypair and opens zed.dev to authorize it — on a remote/headless install, copy the resulting 127.0.0.1 callback URL from your browser's address bar and paste it back here. Distinct from the 'Zed IDE' credential-import entry above: this proxies chat completions through Zed's own hosted model aggregator (cloud.zed.dev), fronting Anthropic/OpenAI/Google/xAI models under your Zed plan.",
  },
  trae: {
    id: "trae",
    serviceKinds: ["llm"],
    alias: "tr",
    name: "Trae",
    icon: "edit_square",
    color: "#FF7849",
    textIcon: "TR",
    website: "https://trae.ai",
    authHint:
      "Trae is an AI-native IDE by ByteDance (SOLO remote agent). Authorize via trae.ai in the popup, or sign in at solo.trae.ai and paste the Cloud-IDE-JWT (sent as 'Authorization: Cloud-IDE-JWT <token>', ~14-day lifetime) as the access token; web_id/biz_user_id/user_unique_id/scope/tenant/region propagate via providerSpecificData. No headless refresh for pasted tokens — re-paste on expiry.",
  },
  "kimi-coding": {
    id: "kimi-coding",
    serviceKinds: ["llm"],
    alias: "kmc",
    name: "Kimi Code CLI",
    icon: "psychology",
    color: "#1E40AF",
    textIcon: "KC",
    // Kimi official-partnership aff link (2026-07) — the "Kimi Coding Plan"
    // tracking link. Was previously unset (no header link rendered at all).
    website: "https://www.kimi.ai/code?aff=omniroute",
    subscriptionRisk: true,
    riskNoticeVariant: "oauth",
    authHint:
      "Sign in with the same Kimi account used by Kimi Code CLI. OmniRoute uses the CLI OAuth flow and Kimi Coding Plan endpoints.",
  },
  kilocode: {
    id: "kilocode",
    serviceKinds: ["llm"],
    alias: "kc",
    name: "Kilo Code",
    icon: "code",
    color: "#FF6B35",
    textIcon: "KC",
    subscriptionRisk: true,
    riskNoticeVariant: "oauth",
    // #4019: serve Kilo's free models without signup. With no account connected,
    // getProviderCredentials synthesizes a noauth credential and the executor
    // sends `Bearer anonymous` (see the kilocode registry `anonymousApiKey`).
    anonymousFallback: true,
    authHint:
      "Sign in with your Kilo Code account (device-code OAuth), or paste a direct API key from app.kilo.ai → Settings → API Keys. Multiple API keys are supported and rotated automatically — add each as a separate connection. Without any connection, free anonymous models are available via the anonymousFallback.",
  },
  cline: {
    id: "cline",
    serviceKinds: ["llm"],
    alias: "cl",
    name: "Cline",
    icon: "smart_toy",
    color: "#5B9BD5",
    textIcon: "CL",
    subscriptionRisk: true,
    riskNoticeVariant: "oauth",
    authHint:
      "Sign in with your Cline account (OAuth), or paste a direct API key from app.cline.bot → Settings → API Keys. Multiple API keys are supported and rotated automatically — add each as a separate connection.",
  },
  clinepass: {
    id: "clinepass",
    serviceKinds: ["llm"],
    alias: "cp",
    name: "ClinePass",
    icon: "smart_toy",
    color: "#9D4EDD",
    textIcon: "CP",
    website: "https://cline.bot/cline-pass",
    subscriptionRisk: true,
    riskNoticeVariant: "oauth",
    authHint:
      "ClinePass is Cline's $9.99/mo subscription bundling 10 open coding models. Sign in with your Cline account (same login as the Cline CLI/IDE), or paste a direct ClinePass API key (app.cline.bot → Settings → API Keys). A ClinePass subscription unlocks the cline-pass/* models. Reuses the Cline WorkOS OAuth flow.",
  },
  "devin-desktop": {
    id: "devin-desktop",
    serviceKinds: ["llm"],
    alias: undefined,
    name: "Devin Desktop",
    icon: "terminal",
    color: "#6366F1",
    textIcon: "DD",
    subscriptionRisk: true,
    riskNoticeVariant: "oauth",
    authHint:
      "Paste an existing Devin API key from an authenticated Devin session. Key export availability and steps vary by Devin version and account.",
    website: "https://devin.ai",
  },
  "devin-cli": {
    id: "devin-cli",
    serviceKinds: ["llm"],
    alias: "dv",
    name: "Devin CLI",
    icon: "terminal",
    color: "#6366F1",
    textIcon: "DV",
    authHint:
      "Requires the Devin CLI binary. Run `devin auth login` to authenticate, or provide your WINDSURF_API_KEY. Install: https://cli.devin.ai",
    website: "https://cli.devin.ai",
  },
  "codebuddy-cn": {
    id: "codebuddy-cn",
    serviceKinds: ["llm"],
    alias: "cbcn",
    name: "CodeBuddy CN",
    icon: "smart_toy",
    color: "#006EFF",
    textIcon: "CB",
    website: "https://copilot.tencent.com",
    subscriptionRisk: true,
    riskNoticeVariant: "oauth",
    authHint:
      "Tencent CodeBuddy CN (copilot.tencent.com). Sign in via the official CLI device-code flow, or paste a direct API key (sent as Authorization: Bearer). Catalog: GLM / Kimi / MiniMax / DeepSeek / Hunyuan.",
  },
  workbuddy: {
    id: "workbuddy",
    serviceKinds: ["llm"],
    alias: "wb",
    name: "WorkBuddy",
    icon: "smart_toy",
    color: "#1A73E8",
    textIcon: "WB",
    website: "https://www.workbuddy.ai",
    subscriptionRisk: true,
    riskNoticeVariant: "oauth",
    // Not to be confused with CodeBuddy CN above: WorkBuddy is a separate
    // Tencent agent platform on its own host and account system, and a
    // CodeBuddy account does not work here.
    authHint:
      "Tencent WorkBuddy (www.workbuddy.ai). Authorize the CLI device flow in the popup; OmniRoute then polls for the token and attaches the required X-Product: SaaS header. The model roster is served by the authenticated catalogue, so it is discovered live rather than listed here. WorkBuddy only accepts streaming requests, which OmniRoute accumulates back into a JSON response for non-streaming callers.",
  },
  "muse-code": {
    id: "muse-code",
    serviceKinds: ["llm"],
    alias: "mc",
    name: "Muse Code (Meta)",
    icon: "auto_awesome",
    color: "#0866FF",
    textIcon: "MC",
    website: "https://ai.developer.meta.com/docs/muse-code/auth",
    subscriptionRisk: true,
    riskNoticeVariant: "oauth",
    passthroughModels: true,
    authHint:
      "Sign in with the Muse Code device flow (same as `muse login` / CLIProxyAPI `-meta-login`) to use a Muse subscription, or paste a META_API_KEY. Device login keeps the durable dca token and mints the inference key; a 401 remints that key. Wire format is OpenAI Responses (POST /responses).",
  },
};
