// GENERATED by scripts/i18n/generate-route-namespaces.mjs — do not edit by hand.
import { SectionI18nProvider } from "@/i18n/SectionI18nProvider";
import sectionNamespaces from "@/i18n/routeNamespaces.generated.json";

/**
 * Per-section i18n provider — serves only the namespaces this section's
 * client components actually use (see scripts/i18n/generate-route-namespaces.mjs).
 */
export default function CombosSectionLayout({ children }: { children: React.ReactNode }) {
  return (
    <SectionI18nProvider namespaces={sectionNamespaces.sections["combos"]}>
      {children}
    </SectionI18nProvider>
  );
}
