export { APP_CONFIG, THEME_CONFIG } from "./appConfig";

// Provider API endpoints (for display only)
export const PROVIDER_ENDPOINTS = {
  seekai: "https://seekai.cc/v1/chat/completions",
  agentrouter: "https://agentrouter.org/v1/chat/completions",
  openrouter: "https://openrouter.ai/api/v1/chat/completions",
  dgrid: "https://api.dgrid.ai/v1/chat/completions",
  bai: "https://api.b.ai/v1/chat/completions",
  qiniu: "https://api.qnaigc.com/v1/chat/completions",
  "zylo-api": "https://api.zyloai.net/v1/chat/completions",
  unorouter: "https://api.unorouter.com/v1/chat/completions",
  poolside: "https://inference.poolside.ai/v1/chat/completions",
  fastrouter: "https://api.fastrouter.ai/api/v1/chat/completions",
  anyapi: "https://api.anyapi.ai/v1/chat/completions",
  beatapi: "https://api.beatapi.io/v1/chat/completions",
  electronhub: "https://api.electronhub.ai/v1/chat/completions",
  llmgateway: "https://api.llmgateway.io/v1/chat/completions",
  lyceum: "https://api.lyceum.technology/openai/v1/chat/completions",
  "llm-kiwi": "https://api.llm.kiwi/v1/chat/completions",
  literouter: "https://api.literouter.com/v1/chat/completions",
  greenpt: "https://api.greenpt.ai/v1/chat/completions",
  onomeo: "https://onomeo.com/v1/chat/completions",
  eurouter: "https://api.eurouter.ai/v1/chat/completions",
  unifically: "https://api.unifically.com/v1/chat/completions",
  "y-api": "https://api.y-api.bestvirtualgoods.com/v1/chat/completions",
  "mnn-ai": "https://api.mnnai.ru/v1/chat/completions",
  "meganova-ai": "https://api.meganova.ai/v1/chat/completions",
  mixlayer: "https://models.mixlayer.ai/v1/chat/completions",
  speka: "https://speka.me/v1/chat/completions",
  tokenreply: "https://api.tokenreply.com/v1/chat/completions",
  "yolo-auto": "https://yolo-auto.com/v1/chat/completions",
  dxnt: "https://www.dxnt.com/v1/chat/completions",
  "cloudcode-one": "https://api.cloudcode.one/v1/chat/completions",
  ofoxai: "https://api.ofox.ai/v1/chat/completions",
  zerolimitai: "https://www.zerolimitai.com/api/v1/chat/completions",
  chatanywhere: "https://api.chatanywhere.org/v1/chat/completions",
  helyxai: "https://helyxai.space/v1/chat/completions",
  auriko: "https://api.auriko.ai/v1/chat/completions",
  "poixe-ai": "https://api.poixe.com/v1/chat/completions",
  "naga-ai": "https://api.naga.ac/v1/chat/completions",
  "chat-oripe": "https://api.oriper.com/v1/chat/completions",
  freeinference: "https://freeinference.org/v1/chat/completions",
  "free-ai": "https://api.free.ai/v1/chat/",
  "void-ai": "https://api.voidai.app/v1/chat/completions",
  helixmind: "https://helixmind.online/v1/chat/completions",
  tabitoken: "https://tabitoken.com/v1/messages",
  glm: "https://api.z.ai/api/anthropic/v1/messages",
  glmt: "https://api.z.ai/api/anthropic/v1/messages",
  "bailian-coding-plan":
    "https://token-plan.ap-southeast-1.maas.aliyuncs.com/apps/anthropic/v1/messages",
  "qwen-cloud": "https://dashscope-intl.aliyuncs.com/compatible-mode/v1/chat/completions",
  "qwen-cloud-token-plan":
    "https://token-plan.ap-southeast-1.maas.aliyuncs.com/compatible-mode/v1/chat/completions",
  kimi: "https://api.moonshot.ai/v1/chat/completions",
  "kimi-coding": "https://api.kimi.com/coding/v1/messages",
  "kimi-coding-apikey": "https://api.kimi.com/coding/v1/messages",
  minimax: "https://api.minimax.io/anthropic/v1/messages",
  "minimax-cn": "https://api.minimaxi.com/anthropic/v1/messages",
  crof: "https://crof.ai/v1/chat/completions",
  apmix: "https://api.apmix.ai/v1/chat/completions",
  zenmux: "https://zenmux.ai/api/v1/chat/completions",
  openadapter: "https://api.openadapter.in/v1/chat/completions",
  dit: "https://api.dit.ai/v1/chat/completions",
  tokenrouter: "https://api.tokenrouter.com/v1/chat/completions",
  "token-kiosk": "https://agent-router.gaib.ai/v1/chat/completions",
  sumopod: "https://ai.sumopod.com/v1/chat/completions",
  x5lab: "https://api.x5lab.dev/v1/chat/completions",
  kenari: "https://kenari.id/v1/chat/completions",
  chenzk: "https://chenzk.top/v1/chat/completions",
  tokenmarket: "https://api.tokensmarket.ai/v1/chat/completions",
  openai: "https://api.openai.com/v1/chat/completions",
  anthropic: "https://api.anthropic.com/v1/messages",
  gemini: "https://generativelanguage.googleapis.com/v1beta/models",
};

// Re-export from providers.js for backward compatibility
export {
  NOAUTH_PROVIDERS,
  OAUTH_PROVIDERS,
  APIKEY_PROVIDERS,
  WEB_COOKIE_PROVIDERS,
  SEARCH_PROVIDERS,
  AUDIO_ONLY_PROVIDERS,
  AI_PROVIDERS,
  AUTH_METHODS,
} from "./providers";

// Re-export from models.js for backward compatibility
export { PROVIDER_MODELS, AI_MODELS } from "./models";
