/**
 * Pricing data — inference-hosts family (serverless GPU / OSS-model hosts + aggregator gateways).
 * Pure data; merged by default-pricing.ts via spread (god-file decomposition; semantic split).
 */
export const DEFAULT_PRICING_INFERENCE = {
  agentrouter: {
    auto: { input: 2.0, output: 8.0 },
  },
  openrouter: {
    auto: {
      input: 2.0,
      output: 8.0,
      cached: 1.0,
      reasoning: 12.0,
      cache_creation: 2.0,
    },
  },
  // Cheaper Inference resale rates — captured from GET /v1/models on 2026-07-31
  // (the catalog reports discount_percent "30.00" against model-maker list price).
  // USD per 1M tokens. `reasoning` mirrors `output`: the gateway bills reasoning
  // tokens at the output rate. Live drift is available via GET /v1/pricing/changes,
  // which is intentionally not auto-synced.
  cheaperinference: {
    "aion-labs.aion-2-0": {
      input: 0.56,
      output: 1.12,
      cached: 0.175,
      reasoning: 1.12,
      cache_creation: 0.56,
    },
    "claude-fable-5": {
      input: 7.0,
      output: 35.0,
      cached: 0.84,
      reasoning: 35.0,
      cache_creation: 10.5,
    },
    "claude-haiku-4.5": {
      input: 1.0,
      output: 5.0,
      cached: 0.1,
      reasoning: 5.0,
      cache_creation: 1.0,
    },
    "claude-opus-4-7-fast": {
      input: 21.0,
      output: 105.0,
      cached: 2.1,
      reasoning: 105.0,
      cache_creation: 21.0,
    },
    "claude-opus-4-8-fast": {
      input: 7.0,
      output: 35.0,
      cached: 0.7,
      reasoning: 35.0,
      cache_creation: 7.0,
    },
    "claude-opus-4.5": {
      input: 3.5,
      output: 17.5,
      cached: 0.42,
      reasoning: 17.5,
      cache_creation: 3.5,
    },
    "claude-opus-4.6": {
      input: 3.5,
      output: 17.5,
      cached: 0.42,
      reasoning: 17.5,
      cache_creation: 3.5,
    },
    "claude-opus-4.7": {
      input: 3.5,
      output: 17.5,
      cached: 0.42,
      reasoning: 17.5,
      cache_creation: 3.5,
    },
    "claude-opus-4.8": {
      input: 4.2,
      output: 21.0,
      cached: 0.42,
      reasoning: 21.0,
      cache_creation: 5.25,
    },
    "claude-opus-5": {
      input: 3.5,
      output: 17.5,
      cached: 0.35,
      reasoning: 17.5,
      cache_creation: 4.375,
    },
    "claude-opus-5-fast": {
      input: 7.0,
      output: 35.0,
      cached: 0.7,
      reasoning: 35.0,
      cache_creation: 8.75,
    },
    "claude-sonnet-4.5": {
      input: 2.1,
      output: 10.5,
      cached: 0.2625,
      reasoning: 10.5,
      cache_creation: 3.2812,
    },
    "claude-sonnet-4.6": {
      input: 2.1,
      output: 10.5,
      cached: 0.252,
      reasoning: 10.5,
      cache_creation: 3.15,
    },
    "claude-sonnet-5": {
      input: 1.4,
      output: 7.0,
      cached: 0.14,
      reasoning: 7.0,
      cache_creation: 1.75,
    },
    "deepseek-v4-flash": {
      input: 0.098,
      output: 0.196,
      cached: 0.0196,
      reasoning: 0.196,
      cache_creation: 0.098,
    },
    "deepseek-v4-pro": {
      input: 0.3045,
      output: 0.609,
      cached: 0.231,
      reasoning: 0.609,
      cache_creation: 0.3045,
    },
    "gemini-2.5-flash": {
      input: 0.21,
      output: 1.75,
      cached: 0.021,
      reasoning: 1.75,
      cache_creation: 0.0583,
    },
    // Live public catalog rate checked 2026-08-16.
    "gemini-3.7-flash": {
      input: 0.525,
      output: 2.625,
      cached: 0.13125,
      reasoning: 2.625,
      cache_creation: 0.017708,
    },
    "gemini-3-flash-preview": {
      input: 0.35,
      output: 2.1,
      cached: 0.049,
      reasoning: 2.1,
      cache_creation: 0.35,
    },
    "gemini-3.1-flash-lite": {
      input: 0.2485,
      output: 1.4913,
      cached: 0.0249,
      reasoning: 1.4913,
      cache_creation: 0.0828,
    },
    "gemini-3.1-pro": {
      input: 2.0,
      output: 12.0,
      cached: 0.2,
      reasoning: 12.0,
      cache_creation: 0.375,
    },
    "gemini-3.1-pro-preview": {
      input: 1.4,
      output: 8.4,
      cached: 0.4375,
      reasoning: 8.4,
      cache_creation: 1.4,
    },
    "glm-4.5": { input: 0.42, output: 1.54, cached: 0.077, reasoning: 1.54, cache_creation: 0.42 },
    "glm-4.5-air": {
      input: 0.14,
      output: 0.77,
      cached: 0.021,
      reasoning: 0.77,
      cache_creation: 0.14,
    },
    "glm-4.6": { input: 0.42, output: 1.54, cached: 0.21, reasoning: 1.54, cache_creation: 0.42 },
    "glm-4.7": { input: 0.42, output: 1.54, cached: 0.11, reasoning: 1.54, cache_creation: 0.42 },
    "glm-5": { input: 0.7, output: 2.24, cached: 0.2, reasoning: 2.24, cache_creation: 0.7 },
    "glm-5.1": { input: 0.98, output: 3.08, cached: 0.2275, reasoning: 3.08, cache_creation: 0.98 },
    "glm-5.2": { input: 0.77, output: 2.42, cached: 0.11, reasoning: 2.42, cache_creation: 0.77 },
    "google/gemini-3.5-flash-lite": {
      input: 0.3,
      output: 2.5,
      cached: 0.03,
      reasoning: 2.5,
      cache_creation: 0.3,
    },
    "gpt-5.4": {
      input: 1.75,
      output: 10.5,
      cached: 0.2191,
      reasoning: 10.5,
      cache_creation: 1.75,
    },
    "gpt-5.4-mini": {
      input: 0.525,
      output: 3.15,
      cached: 0.0656,
      reasoning: 3.15,
      cache_creation: 0.525,
    },
    "gpt-5.5": { input: 3.5, output: 21.0, cached: 0.4375, reasoning: 21.0, cache_creation: 3.5 },
    "gpt-5.6-luna": { input: 0.4, output: 2.4, cached: 0.05, reasoning: 2.4, cache_creation: 0.4 },
    "gpt-5.6-sol": {
      input: 3.5,
      output: 21.0,
      cached: 0.4375,
      reasoning: 21.0,
      cache_creation: 3.5,
    },
    "gpt-5.6-terra": {
      input: 1.0,
      output: 6.0,
      cached: 0.125,
      reasoning: 6.0,
      cache_creation: 1.0,
    },
    "grok-4.5": { input: 1.4, output: 4.2, cached: 0.35, reasoning: 4.2, cache_creation: 1.4 },
    "kimi-k3": { input: 2.1, output: 10.5, cached: 0.2625, reasoning: 10.5, cache_creation: 2.1 },
    "minimax-m2.7": {
      input: 0.168,
      output: 0.672,
      cached: 0.0525,
      reasoning: 0.672,
      cache_creation: 0.168,
    },
  },
  orcarouter: {
    // Orca's own USD/1M base rates, verified 2026-10-08 at
    // https://www.orcarouter.ai/pricing and /models/<full model id>.
    // These are token-price estimates, not exact billed cost. The current
    // calculator does not apply context tiers or timed multipliers (#15151).
    // GPT >272k uses 10/45/1 upstream; this row is the <=272k base tier.
    "openai/gpt-5.5": { input: 5, output: 30, cached: 0.5 },
    "anthropic/claude-opus-4.8": { input: 5, output: 25, cached: 0.5, cache_creation: 6.25 },
    "grok/grok-4.3": { input: 1.25, output: 2.5, cached: 0.2 },
    // DeepSeek applies 2x at 01:00–04:00 and 06:00–10:00 UTC upstream.
    "deepseek/deepseek-v4-pro": { input: 0.66, output: 1.98, cached: 0.022 },
    "minimax/minimax-m2.7": { input: 0.3, output: 1.2, cached: 0.06, cache_creation: 0.375 },
    "qwen/qwen3.7-max": { input: 1.25, output: 3.75, cached: 0.25, cache_creation: 1.563 },
    "google/gemini-3.6-flash": {
      input: 0.75,
      output: 3.75,
      cached: 0.075,
    },
    // orcarouter/auto has no fixed published rate. Keep it unpriced so budget
    // callers can fail closed; absent cache-write prices are not invented.
  },
  synthetic: {
    "hf:openai/gpt-oss-120b": {
      input: 0.1,
      output: 0.1,
      cached: 0.1,
      reasoning: 0,
      cache_creation: 0,
    },
    "hf:zai-org/GLM-5.2": {
      input: 1.4,
      output: 4.4,
      cached: 1.4,
      reasoning: 0,
      cache_creation: 0,
    },
    "hf:moonshotai/Kimi-K2.7-Code": {
      input: 0.95,
      output: 4,
      cached: 0.95,
      reasoning: 0,
      cache_creation: 0,
    },
    "hf:Qwen/Qwen3.6-27B": {
      input: 0.45,
      output: 3.6,
      cached: 0.45,
      reasoning: 0,
      cache_creation: 0,
    },
    "hf:MiniMaxAI/MiniMax-M3": {
      input: 0.6,
      output: 1.2,
      cached: 0.6,
      reasoning: 0,
      cache_creation: 0,
    },
    "hf:zai-org/GLM-4.7-Flash": {
      input: 0.1,
      output: 0.5,
      cached: 0.1,
      reasoning: 0,
      cache_creation: 0,
    },
    "hf:nvidia/NVIDIA-Nemotron-3-Super-120B-A12B-NVFP4": {
      input: 0.3,
      output: 1,
      cached: 0.3,
      reasoning: 0,
      cache_creation: 0,
    },
  },
  groq: {
    "openai/gpt-oss-120b": { input: 0, output: 0, cached: 0, reasoning: 0, cache_creation: 0 },
    "gpt-oss-120b": { input: 0, output: 0, cached: 0, reasoning: 0, cache_creation: 0 },
    "llama-3.3-70b-versatile": { input: 0, output: 0, cached: 0, reasoning: 0, cache_creation: 0 },
    "meta-llama/llama-4-maverick-17b-128e-instruct": {
      input: 0,
      output: 0,
      cached: 0,
      reasoning: 0,
      cache_creation: 0,
    },
    "qwen/qwen3-32b": { input: 0, output: 0, cached: 0, reasoning: 0, cache_creation: 0 },
  },
  fireworks: {
    "accounts/fireworks/models/gpt-oss-120b": {
      input: 0,
      output: 0,
      cached: 0,
      reasoning: 0,
      cache_creation: 0,
    },
    "gpt-oss-120b": { input: 0, output: 0, cached: 0, reasoning: 0, cache_creation: 0 },
    "accounts/fireworks/models/deepseek-v3p1": {
      input: 0,
      output: 0,
      cached: 0,
      reasoning: 0,
      cache_creation: 0,
    },
    "accounts/fireworks/models/llama-v3p3-70b-instruct": {
      input: 0,
      output: 0,
      cached: 0,
      reasoning: 0,
      cache_creation: 0,
    },
    "accounts/fireworks/models/qwen3-235b-a22b": {
      input: 0,
      output: 0,
      cached: 0,
      reasoning: 0,
      cache_creation: 0,
    },
  },
  // #11773: Developer-tier $/1M from cerebras.ai/pricing (2026-09-03).
  // Signup is a one-time $5 credit, not a $0 token grant — keep paid rates
  // so classifyTier cannot treat Cerebras as the free routing tier.
  cerebras: {
    "gpt-oss-120b": { input: 0.35, output: 0.75, cached: 0, reasoning: 0, cache_creation: 0 },
    "gemma-4-31b": { input: 0.4, output: 0.8, cached: 0, reasoning: 0, cache_creation: 0 },
    "zai-glm-4.7": { input: 2.25, output: 2.75, cached: 0, reasoning: 0, cache_creation: 0 },
    "llama-3.3-70b": { input: 0.85, output: 1.2, cached: 0, reasoning: 0, cache_creation: 0 },
    "llama-4-scout-17b-16e-instruct": {
      input: 0.2,
      output: 0.2,
      cached: 0,
      reasoning: 0,
      cache_creation: 0,
    },
    "qwen-3-235b-a22b-instruct-2507": {
      input: 0.6,
      output: 1.2,
      cached: 0,
      reasoning: 0,
      cache_creation: 0,
    },
    "qwen-3-32b": { input: 0.4, output: 0.8, cached: 0, reasoning: 0, cache_creation: 0 },
  },
  nvidia: {
    "nvidia/gpt-oss-120b": { input: 0, output: 0, cached: 0, reasoning: 0, cache_creation: 0 },
    "openai/gpt-oss-120b": { input: 0, output: 0, cached: 0, reasoning: 0, cache_creation: 0 },
    "gpt-oss-120b": { input: 0, output: 0, cached: 0, reasoning: 0, cache_creation: 0 },
    "moonshotai/kimi-k2.5": { input: 0, output: 0, cached: 0, reasoning: 0, cache_creation: 0 },
    "z-ai/glm4.7": { input: 0, output: 0, cached: 0, reasoning: 0, cache_creation: 0 },
    "deepseek-ai/deepseek-v3.2": {
      input: 0,
      output: 0,
      cached: 0,
      reasoning: 0,
      cache_creation: 0,
    },
    "nvidia/llama-3.3-70b-instruct": {
      input: 0,
      output: 0,
      cached: 0,
      reasoning: 0,
      cache_creation: 0,
    },
    "meta/llama-4-maverick-17b-128e-instruct": {
      input: 0,
      output: 0,
      cached: 0,
      reasoning: 0,
      cache_creation: 0,
    },
    "deepseek/deepseek-r1": { input: 0, output: 0, cached: 0, reasoning: 0, cache_creation: 0 },
  },
  nebius: {
    "openai/gpt-oss-120b": { input: 0, output: 0, cached: 0, reasoning: 0, cache_creation: 0 },
    "gpt-oss-120b": { input: 0, output: 0, cached: 0, reasoning: 0, cache_creation: 0 },
    "meta-llama/Llama-3.3-70B-Instruct": {
      input: 0,
      output: 0,
      cached: 0,
      reasoning: 0,
      cache_creation: 0,
    },
  },
  siliconflow: {
    "openai/gpt-oss-120b": { input: 0, output: 0, cached: 0, reasoning: 0, cache_creation: 0 },
    "gpt-oss-120b": { input: 0, output: 0, cached: 0, reasoning: 0, cache_creation: 0 },
    "deepseek-ai/DeepSeek-V3.2": {
      input: 0,
      output: 0,
      cached: 0,
      reasoning: 0,
      cache_creation: 0,
    },
    "deepseek-ai/DeepSeek-V3.1": {
      input: 0,
      output: 0,
      cached: 0,
      reasoning: 0,
      cache_creation: 0,
    },
    "deepseek-ai/DeepSeek-R1": { input: 0, output: 0, cached: 0, reasoning: 0, cache_creation: 0 },
    "Qwen/Qwen3-235B-A22B-Instruct-2507": {
      input: 0,
      output: 0,
      cached: 0,
      reasoning: 0,
      cache_creation: 0,
    },
    "Qwen/Qwen3-Coder-480B-A35B-Instruct": {
      input: 0,
      output: 0,
      cached: 0,
      reasoning: 0,
      cache_creation: 0,
    },
    "Qwen/Qwen3-32B": { input: 0, output: 0, cached: 0, reasoning: 0, cache_creation: 0 },
    "moonshotai/Kimi-K2.5": { input: 0, output: 0, cached: 0, reasoning: 0, cache_creation: 0 },
    "zai-org/GLM-4.7": { input: 0, output: 0, cached: 0, reasoning: 0, cache_creation: 0 },
    "baidu/ERNIE-4.5-300B-A47B": {
      input: 0,
      output: 0,
      cached: 0,
      reasoning: 0,
      cache_creation: 0,
    },
  },
  hyperbolic: {
    "openai/gpt-oss-120b": { input: 0, output: 0, cached: 0, reasoning: 0, cache_creation: 0 },
    "gpt-oss-120b": { input: 0, output: 0, cached: 0, reasoning: 0, cache_creation: 0 },
    "Qwen/QwQ-32B": { input: 0, output: 0, cached: 0, reasoning: 0, cache_creation: 0 },
    "deepseek-ai/DeepSeek-R1": { input: 0, output: 0, cached: 0, reasoning: 0, cache_creation: 0 },
    "deepseek-ai/DeepSeek-V3": { input: 0, output: 0, cached: 0, reasoning: 0, cache_creation: 0 },
    "meta-llama/Llama-3.3-70B-Instruct": {
      input: 0,
      output: 0,
      cached: 0,
      reasoning: 0,
      cache_creation: 0,
    },
    "meta-llama/Llama-3.2-3B-Instruct": {
      input: 0,
      output: 0,
      cached: 0,
      reasoning: 0,
      cache_creation: 0,
    },
    "Qwen/Qwen2.5-72B-Instruct": {
      input: 0,
      output: 0,
      cached: 0,
      reasoning: 0,
      cache_creation: 0,
    },
    "Qwen/Qwen2.5-Coder-32B-Instruct": {
      input: 0,
      output: 0,
      cached: 0,
      reasoning: 0,
      cache_creation: 0,
    },
    "NousResearch/Hermes-3-Llama-3.1-70B": {
      input: 0,
      output: 0,
      cached: 0,
      reasoning: 0,
      cache_creation: 0,
    },
  },
};
