import type { RegistryEntry } from "../../shared.ts";

export const bedrockProvider: RegistryEntry = {
  id: "bedrock",
  alias: "bedrock",
  format: "openai",
  executor: "bedrock",
  authType: "apikey",
  authHeader: "bearer",
  defaultContextLength: 200000,
  models: [
    {
      id: "anthropic.claude-fable-5-1",
      name: "Claude Fable 5.1 (Bedrock)",
      toolCalling: true,
      supportsReasoning: true,
      supportedThinkingEfforts: ["low", "medium", "high", "xhigh", "max"],
      supportsXHighEffort: true,
      supportsVision: true,
      contextLength: 1000000,
      maxOutputTokens: 128000,
    },
    {
      id: "anthropic.claude-opus-5-5",
      name: "Claude Opus 5.5 (Bedrock)",
      toolCalling: true,
      supportsReasoning: true,
      supportedThinkingEfforts: ["low", "medium", "high", "xhigh", "max"],
      supportsXHighEffort: true,
      supportsVision: true,
      contextLength: 1000000,
      maxOutputTokens: 128000,
      unsupportedParams: ["temperature", "top_p", "top_k"],
    },
    {
      id: "anthropic.claude-sonnet-4-6",
      name: "Claude Sonnet 4.6 (Bedrock)",
      toolCalling: true,
      supportsVision: true,
      contextLength: 1000000,
      supportsReasoning: true,
      supportedThinkingEfforts: ["low", "medium", "high", "max"],
    },
    {
      id: "anthropic.claude-sonnet-4-5",
      name: "Claude Sonnet 4.5 (Bedrock)",
      toolCalling: true,
      supportsVision: true,
      contextLength: 200000,
    },
    {
      id: "anthropic.claude-opus-4-6",
      name: "Claude Opus 4.6 (Bedrock)",
      toolCalling: true,
      supportsVision: true,
      contextLength: 1000000,
      supportsReasoning: true,
      supportedThinkingEfforts: ["low", "medium", "high", "max"],
    },
    {
      id: "anthropic.claude-opus-4-7",
      name: "Claude Opus 4.7 (Bedrock)",
      toolCalling: true,
      supportsVision: true,
      contextLength: 1000000,
      supportsReasoning: true,
      supportedThinkingEfforts: ["low", "medium", "high", "xhigh", "max"],
    },
    {
      id: "anthropic.claude-haiku-4-5",
      name: "Claude Haiku 4.5 (Bedrock)",
      toolCalling: true,
      supportsVision: true,
    },
    { id: "openai.gpt-oss-120b-1:0", name: "GPT-OSS 120B (Bedrock)" },
  ],
  passthroughModels: true,
};
