// GENERATED by scripts/i18n/generate-route-namespaces.mjs — do not edit by hand.
import { SectionI18nProvider } from "@/i18n/SectionI18nProvider";
import sectionNamespaces from "@/i18n/routeNamespaces.generated.json";

/**
 * Dashboard home route (`/dashboard`) i18n provider — the "home" set covers
 * page.tsx plus the companion components that live directly under
 * `src/app/(dashboard)/dashboard/`.
 */
export default function DashboardHomeLayout({ children }: { children: React.ReactNode }) {
  return <SectionI18nProvider namespaces={sectionNamespaces.home}>{children}</SectionI18nProvider>;
}
